### ISSUE TITLE
database creation errors

### ISSUE THREAD

**Issue by pingwu** [chef/java-quick-start#3]
Can't figure why fail at database creation.  Need help.  Thanks.

knife ec2 server create -G default -I ami-7000f019 -f m1.small \
-N db1 \
-S inst-sc-rnd -i /tmp/key.pem -x ubuntu \
-r 'role[base],role[dbapp_database_master]'

.............

10.140.15.202 [Fri, 01 Jun 2012 22:27:03 +0000] INFO: Removing cookbooks/git/metadata.json from the cache; its cookbook is no longer needed on this client.
10.140.15.202 [Fri, 01 Jun 2012 22:27:03 +0000] INFO: Missing gem 'mysql'
10.140.15.202 [Fri, 01 Jun 2012 22:27:03 +0000] WARN: Missing gem 'right_aws'
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Could not find previously defined grants.sql resource
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing package[mysql-devel] action install (mysql::client line 20)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing package[mysql-client] action install (mysql::client line 29)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing package[mysql-ruby] action install (mysql::client line 39)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing directory[/var/cache/local/preseeding] action create (mysql::server line 31)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing execute[preseed mysql-server] action nothing (mysql::server line 38)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing template[/var/cache/local/preseeding/mysql-server.seed] action create (mysql::server line 43)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing template[/etc/mysql/debian.cnf] action create (mysql::server line 51)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing package[mysql-server] action install (mysql::server line 60)
10.140.15.202 [Fri, 01 Jun 2012 22:27:04 +0000] INFO: Processing service[mysql] action nothing (mysql::server line 64)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing template[/etc/mysql/my.cnf] action create (mysql::server line 75)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing ruby_block[save node data] action create (mysql::server line 84)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: ruby_block[save node data] called
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing template[/etc/mysql/grants.sql] action create (mysql::server line 115)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing execute[mysql-install-privileges] action nothing (mysql::server line 125)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing template[/etc/mysql/app_grants.sql] action create (database::master line 62)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing execute[mysql-install-application-privileges] action nothing (database::master line 73)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] INFO: Processing mysql_database[create dbapp_production] action create_db (database::master line 84)
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] ERROR: Running exception handlers
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] ERROR: Exception handlers complete
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
10.140.15.202 [Fri, 01 Jun 2012 22:27:05 +0000] FATAL: LoadError: no such file to load -- mysql

**Comment by tas50** [comment]
Closing as this repository has been deprecated
